### ISSUE TITLE
Support interop with ASP.NET Core 2.1 HttpClientFactory

### ISSUE THREAD

**Issue by martincostello** [IdentityServer/IdentityServer4.AccessTokenValidation#105]
_TL;DR_ - Please make [IdentityServer4.AccessTokenValidation](https://github.com/IdentityServer/IdentityServer4.AccessTokenValidation) DI-aware for `HttpClient` usage.

## Details

I'm updating an application targeting ASP.NET Core 2.0 to ASP.NET Core 2.1. As part of this, I'm integrating [HttpClientFactory](https://github.com/aspnet/HttpClientFactory) into the application when creating `HttpClient` instances as it allows delegating message handlers etc. to be easily setup for HTTP calls.

In the 2.0 and 2.1 implementations I intercept HTTP calls to return canned-responses for in-memory testing of dependencies. As part of the 2.0 implementation I use the [`JwtBackChannelHandler`](https://github.com/IdentityServer/IdentityServer4.AccessTokenValidation/blob/3fd88d9ae73734504e269b08901779a7bac1484f/src/IdentityServer4.AccessTokenValidation/IdentityServerAuthenticationOptions.cs#L100) property to provide an `HttpMessageHandler` implementation for use by IdentityServer so that I can return an in-memory generated configuration for JWTs, rather than need to host an endpoint to do so.

However as part of moving this HTTP-related code to use HttpClientFactory for 2.1, I've found an issue where the two implementations don't easily interop with each other.

HttpClientFactory works at the `HttpClient` level and provides no way to return an `HttpMessageHandler` that leverages all the other benefits of the factory, but IdentityServer4.AccessTokenValidation provides extensibility at the `HttpMessageHandler` level and creates its own `HttpClient` instances.

I tried wrapping the `HttpClient` from HttpClientFactory with a custom `HttpMessageHandler` implementation, but due to `HttpClient` being used internally, this fails as the [`HttpRequestMessage`](https://github.com/dotnet/corefx/blob/344c31c7ba9bc171bbab31167acdd279e9f6027c/src/System.Net.Http/src/System/Net/Http/HttpClient.cs#L636-L642) is marked internally as sent before the wrapped code is invoked, and the operation fails.

I've raised a separate issue in the HttpClientFactory repo (aspnet/HttpClientFactory#110) about a future release exposing the ability to access message handlers as well, but making IdentityServer4.AccessTokenValidation support DI-awareness/injection of `HttpClient` somehow would make this scenario easier to achieve.

As a workaround for now, I'm creating an `HttpClient` through the factory, extracting the inner message handler from its private field using reflection, and then assigning that as the value of `JwtBackChannelHandler`, as the implementation used by the factory wraps the real handler and does lifetime tracking. For example:

```csharp
var factory = serviceProvider.GetRequiredService<IHttpClientFactory>();
HttpClient client = factory.CreateClient("MyClient");

FieldInfo field = typeof(HttpMessageInvoker).GetField(
    "_handler",
    BindingFlags.GetField | BindingFlags.Instance | BindingFlags.NonPublic);

options.JwtBackChannelHandler = field.GetValue(client) as HttpMessageHandler;
```

**Comment by leastprivilege** [comment]
Could you elaborate?

**Comment by martincostello** [comment]
So we've got something a bit like this going on in our application using some custom code that we wrap around IdentityService functionality so that common setup for our apps is hidden away in our wrapper library:

```csharp
public static IServiceCollection UseCustomAuthorization(this IServiceCollection services)
{
    var settings = new MyAuthorizationSettings()
    {
        ClientSecret = "ClientSecretFromConfig",
        ClientId = "MyClientIdFromConfig",
    };

    settings.OnBuildServerOptions = (serviceProvider, options) =>
    {
        var factory = serviceProvider.GetRequiredService<IHttpMessageHandlerFactory>();
        options.JwtBackChannelHandler = factory.CreateHandler("Authorize");
    };
}
```

**Comment by leastprivilege** [comment]
OK - I finally looked into this.

This handler is really a decorator over our OAuth2 introspection handler and the Microsoft JWT handler.

Our handler is now HTTP client factory friendly (preview is here: https://www.nuget.org/packages/IdentityModel.AspNetCore.OAuth2Introspection/4.0.0-preview.6). Everything else is Microsoft code that I cannot change.
