### ISSUE TITLE
Registering OAuth2IntrospectionHandler when ApiSecret is not set

### ISSUE THREAD

**Issue by dsmailys** [IdentityServer/IdentityServer4.AccessTokenValidation#107]
Right now when calling AddIdentityServerAuthentication extension method, by default both JWT and Introspection handlers are being registered to the DI.

Would it be possible to resolve IdentityServerAuthenticationOptions early and determine which handlers should and which should not be registered?

The problem we are having is that Microsoft.AspNetCore.Authentication.IAuthenticationSchemeProvider resolves all of the schemas that were registered, including Introspection, which is throwing an exception if ApiSecret is not present (etc when only JWT tokens are used).

**Comment by leastprivilege** [comment]
Why are using this handler when you don't have reference tokens?

**Comment by dsmailys** [comment]
We are not enforcing authentication schemes on the users of our library, but we must make sure that the user is authenticated. Therefore we iterate over registered schemes and try to authenticate the current request. 
As it turns out - IdentityServer4.AccessTokenValidation is quite common among the users.

Actually we are taking a different approach right now, so this is not an issue any more.
