### ISSUE TITLE
AuthenticationSchemeOptions.EventsType not supported by AddIdentityServerAuthentication

### ISSUE THREAD

**Issue by Giorgi** [IdentityServer/IdentityServer4.AccessTokenValidation#109]
### Issue / Steps to reproduce the problem
I am using `IdentityServer4.AccessTokenValidation` to validate jwt tokens and I wanted to log various `JwtBearerEvents` events. I noticed that if I set `options.JwtBearerEvents = new LoggingBearerEvents();` the overriden methods in my class get called but if I set `options.EventsType = typeof(LoggingBearerEvents);` the methods do not get called.

On the other hand if I replace `AddIdentityServerAuthentication` with `AddJwtBearer` everything works fine even if I set it using `options.EventsType = typeof(LoggingBearerEvents);`

Is this scenario not supported by `IdentityServer4.AccessTokenValidation` or is this a bug ?

**Comment by Giorgi** [comment]
@brockallen I think you need to set it on `jwtOptions` instance inside [ConfigureJwtBearer](https://github.com/IdentityServer/IdentityServer4.AccessTokenValidation/blob/master/src/IdentityServerAuthenticationOptions.cs#L154) method

**Comment by Giorgi** [comment]
I added `jwtOptions.EventsType = EventsType;` to the `ConfigureJwtBearer` method and the events get fired but it causes `MessageReceivedContext.Token` to be empty in `MessageReceived` method as the `InternalTokenRetriever` isn't executed any more.

**Comment by leastprivilege** [comment]
Yep there are issues as you found out. It's not supported right now.

**Comment by leastprivilege** [comment]
What's the reason you are using our handler?

**Comment by leastprivilege** [comment]
Either that or implement MessageReceived accordingly.
