### ISSUE TITLE
Local validation

### ISSUE THREAD

**Issue by nicolasr75** [IdentityServer/IdentityServer4.AccessTokenValidation#11]
Since IdSrv and API are in the same process in my project I would like to validate the token locally as was mentioned for IdSrv3 here
https://identityserver.github.io/Documentation/docsv2/consuming/options.html
However, I don't understand how to do this with IdentityServerAuthenticationOptions. There is for example no property SigningCertificate.
What am I missing?

**Comment by leastprivilege** [comment]
If there is no property then this static config is not implemented yet.

Local validation still works - but it will load the config data from the discovery endpoint.

**Comment by nicolasr75** [comment]
My main concern is to avoid having to specify the URL for the Authority because that would in my case mean that users setting up my "Mini API server" would have to configure that URL in some configuration file.
When you say it would use the discovery endpoint, that would still use the Authority URL, right?

In IdentityServerAuthenticationMiddleware.cs I find this:

	// seems to be a JWT
	if (token.Contains('.'))
	{
		// see if local validation is setup
		if (_jwtNext != null)
		{
			await _jwtNext(context);
			return;
		}
		// otherwise use introspection endpoint
		if (_introspectionNext != null)
		{
			await _introspectionNext(context);
			return;
		}

		_logger.LogWarning("No validator configured for JWT token");
	}
	else
	{
		// use introspection endpoint
		if (_introspectionNext != null)
		{
			await _introspectionNext(context);
			return;
		}

		_logger.LogWarning("No validator configured for reference token");
	}

But I don't understand what it means. This code seems to assume that local validation could be set up, but how?

**Comment by leastprivilege** [comment]
Static configuration is not supported yet.

Local means - no introspection.
