### ISSUE TITLE
Question: Introspection endpoint being called on each request

### ISSUE THREAD

**Issue by nixa333** [IdentityServer/IdentityServer4.AccessTokenValidation#112]
Hi,

I have a simple API in ASP.NET core which uses IS4 for authentication needs. 
API is split in two different versions; newer one supports OAuth and actually uses IS4, but the older one is secured via my custom authorization which uses Authorization header in request to pass token to the API. I've noticed that IS4 server's introspection endpoint is being called on each request to my **old API** endpoints whenever they're called with **Authorization: Bearer 1234567890asdfgh** even though the API controller isn't decorated with [Authorize] attribute.
I'm interested in knowing why is that, and is there a way it can be stopped?

**Comment by leastprivilege** [comment]
That how asp.net core works.

**Comment by leastprivilege** [comment]
That being said, you could not set the handler as the default authentication scheme, and call AuthenticateAsync yourself in your new apis

**Comment by nixa333** [comment]
For the record, I went on and implemented my custom Authentication handler instead of using IS4. 
I ended up reusing bunch of IS4 code and couple of classes to save time. 
This is a temporary solution as we intend to deprecate the old API in the near future, so we'll revert to the IS4 handler.

**Comment by bloodybeet** [comment]
We see the same "issue": introspect is being hit every time, even though our caching is on. This wasn't the case for IdentityServer3. Looks like a combination of the following lines enforces introspect to happen every time, even though the claims could be cached:
`var lazyIntrospection = Options.LazyIntrospections.GetOrAdd(token, CreateLazyIntrospection);`
`finally
            {
                // If caching is on and it succeeded, the claims are now in the cache.
                // If caching is off and it succeeded, the claims will be discarded.
                // Either way, we want to remove the temporary store of claims for this token because it is only intended for de-duping fetch requests
                Options.LazyIntrospections.TryRemove(token, out _);
            }`
