### ISSUE TITLE
Does IdentityServer4.AccessTokenValidation only works in IdentityServer 4 ?

### ISSUE THREAD

**Issue by madhub** [IdentityServer/IdentityServer4.AccessTokenValidation#113]
Hi 
I am using **IdentityServer4.AccessTokenValidation** nuget to do **OAUTH2 introspection** to 3rd party **OAUTH2 server**, is it recommended to use  IdentityServer4.AccessTokenValidation for any 3rd party **OAUTH2 server**.
If yes, how do I configure it to send the **clientid & client secret** in  **Http Authoriztion Header** , currently its sends in HTTP POST body.

Madhu

**Comment by leastprivilege** [comment]
As the name implies, we only care about compat with Identityserver

**Comment by madhub** [comment]
Ok, how about **IdentityModel.AspNetCore.OAuth2Introspection** does it supports 3rd party **OAUTH2 server**.

If yes, how do I configure it to send the **clientid & client secret in Http Authoriztion Header** , currently its sends in HTTP POST body.

**Comment by leastprivilege** [comment]
It's implemented on the v4 branch - 

https://github.com/IdentityModel/IdentityModel.AspNetCore.OAuth2Introspection/blob/v4/src/OAuth2IntrospectionOptions.cs#L51

Nuget is here:
https://www.nuget.org/packages/IdentityModel.AspNetCore.OAuth2Introspection/4.0.0-aultmore

I am planning to release this soon. give it a try.

**Comment by madhub** [comment]
Ok, will try out.

I see the example in the [oauth introspection spec](https://www.oauth.com/oauth2-servers/token-introspection-endpoint/) showing sending **client id & secret** in **authorization header**, curious to know the reason behind sending **client id & client secret** in HTTP body instead of **authorization header** in **IdentityServer4.AccessTokenValidation** & **IdentityModel.AspNetCore.OAuth2Introspection** library.

**Comment by leastprivilege** [comment]
They are both allowed. Please open a feedback issue in the introspection repo.
