### ISSUE TITLE
Exception does not show anything in logs ( try/finally)-IdentityServerAuthenticationHandler

### ISSUE THREAD

**Issue by lisberPontes** [IdentityServer/IdentityServer4.AccessTokenValidation#116]
Exception does not show anything in logs ( try/finally)-IdentityServerAuthenticationHandler

After some hourse digging why something didn't work properly in localhost (it ended up been a missconfiguration in my ids).

I took the sourcecode and saw that there's a try/finally block without a catch (in case something happen just log it).

**Comment by lisberPontes** [comment]
I've a commit I wish to send you as a PR:
![image](https://user-images.githubusercontent.com/20478619/57091423-736a7280-6d09-11e9-91d9-56b7a4bfeea1.png)

May I have permissions to create a remote branch and send you a PR ?

Regards,

**Comment by leastprivilege** [comment]
yes please.

**Comment by lisberPontes** [comment]
> yes please.

I still cannot publish my remote branch in order to send you a PR :(

![image](https://user-images.githubusercontent.com/20478619/57136263-8d10c600-6dac-11e9-8943-e60c9a45490e.png)


May you please give permissions to my account so that I can publish my remote branch?
Regards,
Lisber

**Comment by leastprivilege** [comment]
You don't need any permissions to do a PR.
