### ISSUE TITLE
Why are IdentityServerAuthenticationDefaults internal?

### ISSUE THREAD

**Issue by VictorioBerra** [IdentityServer/IdentityServer4.AccessTokenValidation#117]
https://github.com/IdentityServer/IdentityServer4.AccessTokenValidation/blob/594d8040e5b0aec4d9a9295a6eb5e9f68921432b/src/IdentityServerAuthenticationDefaults.cs#L16

This means I can't reference those if I need to call `AddIdentityServerAuthentication` twice and later reference the scheme i want, like in an Authorize Attribute for example.

**Comment by leastprivilege** [comment]
They are internal for a good reason: they are only used internally. You use whatever scheme you specify when adding the handler.
