### ISSUE TITLE
Does it work with .net framework 4.7.2?

### ISSUE THREAD

**Issue by TeemoHQ** [IdentityServer/IdentityServer4.AccessTokenValidation#121]

**Comment by leastprivilege** [comment]
yes

**Comment by TeemoHQ** [comment]
Thank you for your reply, please ask where there are examples, I did not find。（AccessTokenValidation4 & framwork 4.7.2 webapi）

**Comment by TeemoHQ** [comment]
> yes

Thank you for your reply, please ask where there are examples, I did not find。（AccessTokenValidation4 & framwork 4.7.2 webapi）

**Comment by TeemoHQ** [comment]
> yes

Thank you for your reply, please ask where there are examples, I did not find。（AccessTokenValidation4 & framwork 4.7.2 webapi）
