### ISSUE TITLE
when i upgrade to identitymode version 4

### ISSUE THREAD

**Issue by pigwing** [IdentityServer/IdentityServer4.AccessTokenValidation#124]
Could not load type 'IdentityModel.Client.DiscoveryClient' from assembly 'IdentityModel, Version=4.0.0.0, Culture=neutral, PublicKeyToken=e7877f4675df049f'

and the version 3 preview.2 is ok

**Comment by leastprivilege** [comment]
Don't upgrade.

**Comment by pigwing** [comment]
ok,and then i upgrade IdentityServer4.AccessTokenValidation to version 3 preview.2 the problem solved

**Comment by leastprivilege** [comment]
I will release a final version in the coming weeks.

**Comment by pigwing** [comment]
thanks very much

**Comment by koo9** [comment]
the nuget package IdentityServer4.AccessTokenValidation shows up as update but when installing it, it says not compatible with the project. looks like it's for core 3.0 but not core 2.2. any idea?
