### ISSUE TITLE
Is .NETStandard still supported?

### ISSUE THREAD

**Issue by MikeChristensen** [IdentityServer/IdentityServer4.AccessTokenValidation#126]
It looks like 3.x targets .NET Core, while 2.x targets .NET Standard.  Any plans to create a .NET Standard version of 3.x for people who are running ASP.NET Core on .NET Framework?

**Comment by leastprivilege** [comment]
No. Because 3.x targets ASP.NET Core 3 - which only runs on .NET Core.

**Comment by leastprivilege** [comment]
.NET Framework is "done" yes.
