### ISSUE TITLE
Spelling error on documentation comment

### ISSUE THREAD

**Issue by rhtnr** [IdentityServer/IdentityServer4.AccessTokenValidation#127]
Spell check fail at 

Line  88 master `src/IdentityServerAuthenticationOptions.cs`

    ` " /// Gets or sets the _**policay**_ for the introspection discovery document."`

**Comment by leastprivilege** [comment]
thanks. Want to fix it yourself?

**Comment by rhtnr** [comment]
I have submitted a pull request
