### ISSUE TITLE
Send extra parameters on reference token validation

### ISSUE THREAD

**Issue by jrcpereira** [IdentityServer/IdentityServer4.AccessTokenValidation#129]
Hi!

Is there any way to pass extra parameters to Ids on token validation?

I would like to retain IP address and a timestamp for each token validated on Ids.
Since validation occurs server side, it would be great if we could pass additional parameters to the Ids endpoint.

Thanks!

**Comment by leastprivilege** [comment]
You can inject your own HTTP message handler which could add data for outgoing calls..

**Comment by jrcpereira** [comment]
Thanks for the hint!

Just to be sure I got it right... The best solution is to inject my message handler and create the HttpClient for introspection before the call to add IdentityServerAuthentication, right?

`            services.AddScoped<CustomHttpMessageHandler>();
            services.AddHttpClient(OAuth2IntrospectionDefaults.BackChannelHttpClientName)
                .ConfigurePrimaryHttpMessageHandler<CustomHttpMessageHandler>();
`

**Comment by leastprivilege** [comment]
It does not need to be the primary one - that's usually reserved for network config related things...

**Comment by jrcpereira** [comment]
Despite I named it _CustomHttpMessageHandler_, I derived it from the _HttpClientHandler_.
But I will just add it as another handler to the HttpClient, just in case.

Thanks, once again!
