### ISSUE TITLE
How to delete a reference token from API in distributed cache?

### ISSUE THREAD

**Issue by SpiritBob** [IdentityServer/IdentityServer4.AccessTokenValidation#130]
When I pass the reference token as key to the Get method of the distributed cache implementation, it returns null. After inspecting with a debugger, the keys used inside the memory cache implementation have nothing in common with a reference token.

What exactly are they, and is there a way to delete them when I know a given user's reference token?

**Comment by leastprivilege** [comment]
I can't remember. Maybe I hash them before putting in the cache. The code is here:

https://github.com/IdentityModel/IdentityModel.AspNetCore.OAuth2Introspection

**Comment by SpiritBob** [comment]
Yeah, you're hashing them in SHA256. I forgot to close this, thank you.
