### ISSUE TITLE
How does caching (reference token validation) work? I need to invalidate cache when user resets the password. Please help.

### ISSUE THREAD

**Issue by PrashanthShetty** [IdentityServer/IdentityServer4.AccessTokenValidation#131]
### Minimal working example

```csharp
   // <code goes here>
```

### Relevant parts of the log file

```
   <log goes here>
```

**Comment by leastprivilege** [comment]
It uses whatever IDistributedCache is registered. So use your caching system to do that.

Also - be aware that caching for a longer time - let's say more than 10 seconds is not recommended. Anything else would defeat the purpose of reference tokens.

**Comment by PrashanthShetty** [comment]
Thank you, I think If I can get the key, i.e.   
var cacheKey = $"{CacheKeyPrefix}{token}".Sha256(); and then 
_distributedCache.Remove(cacheKey);
I can invalidate the cache.

**Comment by leastprivilege** [comment]
this library is deprecated in favour of this superior and more flexible approach:

https://leastprivilege.com/2020/07/06/flexible-access-token-validation-in-asp-net-core/
