### ISSUE TITLE
Unable to configure httpClient of HttpDocumentRetriever.

### ISSUE THREAD

**Issue by maliming** [IdentityServer/IdentityServer4.AccessTokenValidation#138]
hi

If the Identity Server uses http2, `HttpDocumentRetriever ` will not work unless we can configure `httpClient `. (`DefaultRequestVersion = new Version(2, 0)`)

https://docs.microsoft.com/en-us/dotnet/core/whats-new/dotnet-core-3-0#http2-support

```cs
 var httpClient = new HttpClient(JwtBackChannelHandler ?? new HttpClientHandler()) 
 { 
     Timeout = BackChannelTimeouts, 
     MaxResponseContentBufferSize = 1024 * 1024 * 10, // 10 MB 
     DefaultRequestVersion = new Version(2, 0)
 }; 
```

https://github.com/IdentityServer/IdentityServer4.AccessTokenValidation/blob/8a6bd7ebafc31a76068a9b6863eec94739ec2990/src/IdentityServerAuthenticationOptions.cs#L169-L181

**Comment by leastprivilege** [comment]
see here https://leastprivilege.com/2020/07/06/flexible-access-token-validation-in-asp-net-core/

**Comment by maliming** [comment]
Thanks! 👍
