### ISSUE TITLE
Automatic scope validation?

### ISSUE THREAD

**Issue by SpiritBob** [IdentityServer/IdentityServer4.AccessTokenValidation#139]
The [docs](https://identityserver4.readthedocs.io/en/latest/quickstarts/1_client_credentials.html#authorization-at-the-api) showing an example of protecting an API with client credentials explains how we need to create our own policy for validating api scopes, in order to make sure that the token coming in has access to use our API.

This doesn't seem to be the case when using IdentityServer4.AccessTokenValidation.

It seems it automatically checks for the scope against `IdentitySererAuthenticationOptions.ApiName`.

Is this correct? I couldn't find the code where it does that.

**Comment by leastprivilege** [comment]
The handler does not check scopes.

That being said - I will deprecate this repo in favour of:

https://leastprivilege.com/2020/07/06/flexible-access-token-validation-in-asp-net-core/
