### ISSUE TITLE
Difference from Microsoft.AspNetCore.Authentication.OpenIdConnect

### ISSUE THREAD

**Issue by Marfusios** [IdentityServer/IdentityServer4.AccessTokenValidation#16]
Hello,

What's the difference between this nuget and  "Microsoft.AspNetCore.Authentication.OpenIdConnect": "1.0.0-rc2-final" ?

Is there any correlation? 

There is a method "app.UseOpenIdConnectAuthentication(options)" and it seems very similar and more production ready.

**Comment by leastprivilege** [comment]
One if for OpenID Connect and one is for validating access tokens.
