### ISSUE TITLE
Identity Server 3 compatibility

### ISSUE THREAD

**Issue by senj** [IdentityServer/IdentityServer4.AccessTokenValidation#17]
Hi,

I'm writing Services with Asp.Net Core but we still have an Identity Server 3.
Can I use Token Validation in Core with the Identity Server 3?

Thanks..

**Comment by leastprivilege** [comment]
yes

**Comment by valeriob** [comment]
I'm not able to use IdentityServer4.AccessTokenValidation against identity server 3 with reference token.

AccessTokenValidation v3 config : 
`
 app.UseIdentityServerBearerTokenAuthentication(new IdentityServerBearerTokenAuthenticationOptions
            {
                Authority = "https://localhost:44333/core",
                RequiredScopes = new[] { "myScope" },
            });
`

AccessTokenValidation v4 config : 

`
   app.UseIdentityServerAuthentication(new IdentityServerAuthenticationOptions
            {
                Authority = "https://localhost:44333/core",
                ScopeName = "myScope",
            });
`


i get 401 and i'm not able to diagnose the problem, i've no clue what UseOAuth2IntrospectionAuthentication is :D

I could get the system working by using JWT token with Microsoft.AspNetCore.Authentication.JwtBearer thought

**Comment by leastprivilege** [comment]
you need to specify a scope secret.

Unauthenticated token introspection is not supported anymore in idsrv4

**Comment by valeriob** [comment]
Ouch, that's an entire afternoon gone :D now it works
