### ISSUE TITLE
Improved standard config

### ISSUE THREAD

**Issue by leastprivilege** [IdentityServer/IdentityServer4.AccessTokenValidation#2]
Since we could not fix that in the old version:

```csharp
var options = new IdentityServerBearerTokenOptions
{
   Authority = "https://...",
   ScopeName = "api1",
   ScopeSecret = "secret"

   // optional
   AdditionalScopes = new[] { "foo", "bar" }
}
```

**Comment by leastprivilege** [comment]
We also do not need support for the old access token validation endpoint anymore. Introspection only.

**Comment by tugberkugurlu** [comment]
Cool, if this is going to be only for Introspection, should we rename the middleware (and maybe the project) name to something which indicates this?

For `ScopeName` and `ScopeSecret`, like this (in progress):

https://github.com/tugberkugurlu/IdentityServer4.AccessTokenValidation/blob/73575e7c8efa073d310c9c4f5f1836e84e53b82f/src/IdentityServer4.AccessTokenValidation/IdentityServerBearerTokenOptions.cs#L24-L38

**Comment by leastprivilege** [comment]
Introspection & jwt

**Comment by leastprivilege** [comment]
Also `ScopeName` will serve both introspection authN as well as scope validation (you'd need to reflect that in the comment)

**Comment by tugberkugurlu** [comment]
So, scope validation will combine `ScopeName` and `AdditionalScopes` collection, correct? 

What should happen when user specifies a scope as `ScopeName` and aslo in the `AdditionalScopes` collection? Throw or Distinct the scopes and carry on silently?

**Comment by leastprivilege** [comment]
Distinct. 

Logically i would design them as three different middlewares- introspection, jwt and scope validation. Each with their own extension ( and options?) and one main extension with its options  that does tie them together and does the pipeline branching.
