### ISSUE TITLE
Exception thrown when loading application, version mismatch on reference to Microsoft.IdentityModel.Tokens?

### ISSUE THREAD

**Issue by rocketrave** [IdentityServer/IdentityServer4.AccessTokenValidation#21]
I'm using the 1.0.0-beta9 version of this project in a project running the RTM version of core and preview 2 of tooling, and my application crashes during startup.
It fails during the application builder call to UseIdentityServerAuthentication() with the following exception:

> Exception thrown: 'System.IO.FileLoadException' in IdentityServer4.AccessTokenValidation.dll
>
Additional information: Could not load file or assembly 'Microsoft.IdentityModel.Tokens, Version=5.0.0.699, Culture=neutral, PublicKeyToken=31bf3856ad364e35'. The located assembly's manifest definition does not match the assembly reference. (Exception from HRESULT: 0x80131040)

Stack trace: 
>at Microsoft.AspNetCore.Builder.IdentityServerAuthenticationExtensions.ConfigureJwt(IdentityServerAuthenticationOptions options)
   at Microsoft.AspNetCore.Builder.IdentityServerAuthenticationExtensions.UseIdentityServerAuthentication(IApplicationBuilder app, IdentityServerAuthenticationOptions options)
... (my code)

**Comment by leastprivilege** [comment]
theres a 1.0.1 version that fixes that
