### ISSUE TITLE
IdentityServer4 and .NET Framework

### ISSUE THREAD

**Issue by ivanmariychuk** [IdentityServer/IdentityServer4.AccessTokenValidation#25]
Hello! Maybe weird question but can't understand, if I want to validate access tokens from IdentityServer4 on resource server which uses .NET 4.5 (not .NET Core) how can I do it?

**Comment by leastprivilege** [comment]
You can use the plain JWT middleware from Katana - or our IdentityServer3.AccessTokenValidation middleware.

**Comment by ivanmariychuk** [comment]
Thanks, that works fine for me!
