### ISSUE TITLE
Getting http 403 when calling api

### ISSUE THREAD

**Issue by cuiliang** [IdentityServer/IdentityServer4.AccessTokenValidation#26]
I am using UseJwtBearerAuthentication() in a api project, but always got http 403 when calling api.

code in Config() of the api project:
```
            app.UseIdentityServerAuthentication(new IdentityServerAuthenticationOptions
            {
                Authority = "http://localhost:8000",
                ScopeName = "api1",
                RequireHttpsMetadata = false
            });
```
debug info:
![image](https://cloud.githubusercontent.com/assets/1972649/18517931/b50fafc6-7ad0-11e6-9529-0a426ef4e05d.png)
You an see there is no warning, but returned 403.

But it will pass if use UseJwtBearerAuthentication() like this:
```
app.UseJwtBearerAuthentication(new JwtBearerOptions
            {
                Authority = "http://localhost:8000",
                Audience = "http://localhost:8000/resources",
                AutomaticChallenge = true,
                AutomaticAuthenticate = true,
                RequireHttpsMetadata = false
            });
```
debug info:
![image](https://cloud.githubusercontent.com/assets/1972649/18518204/a94843fa-7ad1-11e6-89d9-dbcaca18560d.png)

Code in OP server's ConfigureServices():
```
services.AddIdentityServer()
                .SetSigningCredential(cert)
                .AddInMemoryStores()
                .AddInMemoryScopes(IdentityServerConfig.GetScopes())
                .AddInMemoryClients(IdentityServerConfig.GetClients())
                .AddAspNetIdentity<ApplicationUser>();
```

Am i doing something wrong?

thanks.

**Comment by cuiliang** [comment]
message diff:
![image](https://cloud.githubusercontent.com/assets/1972649/18518531/f741799a-7ad2-11e6-8052-6a4591482f8f.png)

**Comment by leastprivilege** [comment]
Looks like your token does not have the requires scope?

**Comment by cuiliang** [comment]
@leastprivilege 
Yes, it can pass now after I add scope to request url.  Thank you very much.
It's better to give some warning message for users (who are not familiar with the protocol) to identify  problem.
