### ISSUE TITLE
JwtBearer Events

### ISSUE THREAD

**Issue by ademcaglin** [IdentityServer/IdentityServer4.AccessTokenValidation#27]
Is there a way to use JwtBearer events?

For example i want to implement something like below :

```
app.UseIdentityServerAuthentication(new IdentityServerAuthenticationOptions()
 {
     // ...
     Events = new JwtBearerEvents()
     {
          OnAuthenticationFailed = async (context) =>
          {
              if (condition)
              {
                   context.SkipToNextMiddleware();
              }
          }
     }
 });
```

**Comment by leastprivilege** [comment]
Hi, 

not right now. Why do you need to handle this event?

You can always use the JWT bearer middleware directly.

**Comment by ademcaglin** [comment]
Actually i haven't needed yet. However when i tried to answer [this ](http://stackoverflow.com/questions/39580825/multiple-authentication-middlewares-asp-net-core)so question, i noticed that there is no event support. I wondered if it is possible with anyway.

**Comment by leastprivilege** [comment]
Not right now - do you have a use case for it?

**Comment by ademcaglin** [comment]
Suppose that you want to implement [token revocation ](https://tools.ietf.org/html/rfc7009#section-2) mechanism for jwt token(it might not matter for reference token).  I think `TokenValidated` event of `JwtBearerAuthentication ` can be used for it like https://docs.asp.net/en/latest/security/authentication/cookie.html#reacting-to-back-end-changes.
