### ISSUE TITLE
Question

### ISSUE THREAD

**Issue by johnkors** [IdentityServer/IdentityServer4.AccessTokenValidation#29]
Any reason this NuGet / repo name contains "IdentityServer4"? Are there really anything that ties the validation of access tokens to idsrv4 specifically?

**Comment by leastprivilege** [comment]
Well - it is generation4 for .net core.

**Comment by johnkors** [comment]
Ok - just wondered if this was doing anything new other than the previous local / endpoint based validation that only worked with idsrv4. 

So this should work with tokens from other token providers then. Thx.

**Comment by leastprivilege** [comment]
Are you seeing other providers? I am shocked.

**Comment by johnkors** [comment]
Yeah, IdSrv3! ;) #oldschool

**Comment by leastprivilege** [comment]
;)
