### ISSUE TITLE
Target dotnet5.4 and net451

### ISSUE THREAD

**Issue by tugberkugurlu** [IdentityServer/IdentityServer4.AccessTokenValidation#3]
Currently, [Microsoft.AspNet.Authentication.JwtBearer](https://github.com/aspnet/Security/tree/dev/src/Microsoft.AspNet.Authentication.JwtBearer) package targets dnx451 and dnxcore50. [Not sure why](https://github.com/aspnet/Security/issues/590) but when it is fixed, we can change this project to target dotnet5.4 and net451.

**Comment by uncleyo** [comment]
It will probably be netstandard1.3 instead of dotnet5.4, if I understand the upcoming changes correctly.

**Comment by leastprivilege** [comment]
right - upcoming ;)

**Comment by kalllol** [comment]
Is this fixed? 
i ran into a compile issue today and created an issue #9 
i wonder if the root cause is the Microsoft package mentioned in issue #3
