### ISSUE TITLE
Access Token lost somewhere

### ISSUE THREAD

**Issue by SaschaHerrmann** [IdentityServer/IdentityServer4.AccessTokenValidation#31]
Hi,

related Issue: #17 

I have a similar problem like in the issue above. I am using IdSrv 3 with IdSrv-4-AccessTokenValidation. 
I can authenticate with a resource client, a custom grant client but not with the access token from my implicit auth web site. Authentication works to a point but the result is 401.
The access token is validated successfully, the user is authenticated but the token gets lost somehow in the internal redirect. 

My configuration:

`//JwtSecurityTokenHandler.DefaultInboundClaimTypeMap = new Dictionary<string, string>();

            application.UseIdentityServerAuthentication(new IdentityServerAuthenticationOptions()
            {
                Authority =
                    ((IOptions<IdentityServerSettings>)serviceProvider.GetService(typeof(IOptions<IdentityServerSettings>)))
                        .Value.IdentityServerBaseAddress,

                ScopeName = "importserverapi",

                RoleClaimType = "role",
                NameClaimType = "name",

                EnableCaching = false,
                RequireHttpsMetadata = true
            });`

Enabling the line
`JwtSecurityTokenHandler.DefaultInboundClaimTypeMap = new Dictionary<string, string>();`
does not make any difference.

This ist the log from VS for one request (I replaced the real names):

> The thread 0x2b98 has exited with code 0 (0x0).
The thread 0x418c has exited with code 0 (0x0).
The thread 0x2280 has exited with code 0 (0x0).
Microsoft.AspNetCore.Hosting.Internal.WebHost: Information: Request starting HTTP/1.1 GET http://localhost:44309/MYLINK  
Microsoft.AspNetCore.Authentication.JwtBearer.JwtBearerMiddleware: Information: Successfully validated the token.
Microsoft.AspNetCore.Authentication.JwtBearer.JwtBearerMiddleware: Information: HttpContext.User merged via AutomaticAuthentication from authenticationScheme: Bearer.
Microsoft.AspNetCore.Authentication.JwtBearer.JwtBearerMiddleware: Information: AuthenticationScheme: Bearer was successfully authenticated.
IdentityModel.AspNetCore.ScopeValidation.ScopeValidationMiddleware: Information: Scopes found on current principal: scope: openid, scope: profile, scope: email, scope: roles, scope: MYSCOPE
Microsoft.AspNetCore.Authorization.DefaultAuthorizationService: Information: Authorization was successful for user: USERNAME.
Microsoft.AspNetCore.Mvc.Internal.RedirectResultExecutor: Information: Executing RedirectResult, redirecting to https://localhost:44309/MYLINK.
Microsoft.AspNetCore.Mvc.Internal.ControllerActionInvoker: Information: Executed action Import.Api.Controllers.MYCONTROLLER.MYACTION (Api) in 2.326ms
**Microsoft.AspNetCore.Hosting.Internal.WebHost:_ Information: Request finished in 10.99ms 301 
Microsoft.AspNetCore.Hosting.Internal.WebHost: Information: Request starting HTTP/1.1 GET http://localhost:44309/MYLINK  
IdentityServer4.AccessTokenValidation.Infrastructure.NopAuthenticationMiddleware: Information: Bearer was not authenticated. Failure message: No token found.**
Microsoft.AspNetCore.Authorization.DefaultAuthorizationService: Information: Authorization failed for user: .
Microsoft.AspNetCore.Mvc.Internal.ControllerActionInvoker: Warning: Authorization failed for the request at filter 'Microsoft.AspNetCore.Mvc.Authorization.AuthorizeFilter'.
Microsoft.AspNetCore.Mvc.ChallengeResult: Information: Executing ChallengeResult with authentication schemes ().
IdentityServer4.AccessTokenValidation.Infrastructure.NopAuthenticationMiddleware: Information: AuthenticationScheme: Bearer was challenged.
Microsoft.AspNetCore.Hosting.Internal.WebHost: Information: Request finished in 7.0371ms 401

What is happening here? I searched for days without any clue why the token is lost in the redirect.
I read the docs, read the issues and debugged but with no luck.

**Comment by leastprivilege** [comment]
> the user is authenticated but the token gets lost somehow in the internal redirect.

I don't know what that means?

**Comment by brockallen** [comment]
Any update on this issue?

**Comment by SaschaHerrmann** [comment]
Hi,

sorry for the delay.

> I don't know what that means

In the logs above there is a first request which gets authenticated. I do not know why there is a second request which is not authenticated:

`Microsoft.AspNetCore.Hosting.Internal.WebHost:_ Information: Request finished in 10.99ms 301
Microsoft.AspNetCore.Hosting.Internal.WebHost: Information: Request starting HTTP/1.1 GET http://localhost:44309/MYLINK
IdentityServer4.AccessTokenValidation.Infrastructure.NopAuthenticationMiddleware: Information: Bearer was not authenticated. Failure message: No token found.`


I did not have time to investigate the problem here. I will do so when i updated my projects to the new dotnet version 1.1. As soon as i have more on this I will post it here.

**Comment by leastprivilege** [comment]
Will close for now - feel free to re-open when needed.

**Comment by Keithleo9008** [comment]
I have the same problem

**Comment by SaschaHerrmann** [comment]
Update
I think i have found the problem. I had a middleware active which redirected to the url with a trailing slash. This caused the token to be lost.
@Keithleo9008 If you happen to have something active like "redirecttocanonical", deactivate it and try again. Should work.
