### ISSUE TITLE
Problem with Core 1.1

### ISSUE THREAD

**Issue by imperugo** [IdentityServer/IdentityServer4.AccessTokenValidation#33]
Hi, 
today I've updated my application with hte newest 1.1 and it seems something doesn't work.
All the requests, included the cookies authentication, are returning 401.

Here the console output:

```console
info: Microsoft.AspNetCore.Hosting.Internal.WebHost[1]
      Request starting HTTP/1.1 GET https://www-dev.bmwucportal.it:5000/
info: IdentityServer4.AccessTokenValidation.Infrastructure.NopAuthenticationMiddleware[7]
      Bearer was not authenticated. Failure message: No token found.
info: Microsoft.AspNetCore.Authorization.DefaultAuthorizationService[2]
      Authorization failed for user: (null).
info: Microsoft.AspNetCore.Mvc.Internal.ControllerActionInvoker[1]
      Authorization failed for the request at filter 'Microsoft.AspNetCore.Mvc.Authorization.AuthorizeFilter'.
info: Microsoft.AspNetCore.Mvc.ChallengeResult[1]
      Executing ChallengeResult with authentication schemes ().
info: Microsoft.AspNetCore.Authentication.OpenIdConnect.OpenIdConnectMiddleware[12]
      AuthenticationScheme: oidc was challenged.
info: IdentityServer4.AccessTokenValidation.Infrastructure.NopAuthenticationMiddleware[12]
      AuthenticationScheme: Bearer was challenged.
info: Microsoft.AspNetCore.Mvc.Internal.ControllerActionInvoker[2]
      Executed action Gaia.Bmw.Remarketing.Controllers.HomeController.Index (Gaia.Bmw.Remarketing) in 374.4128ms
info: Microsoft.AspNetCore.Hosting.Internal.WebHost[2]
      Request finished in 799.5424ms 401
```

My security configuration is more or less like this:

```csharp
app.UseIdentityServerAuthentication(new IdentityServerAuthenticationOptions
{
    Authority = urlBuilderConfiguration.Auth.Url,
    RequireHttpsMetadata = false,
    ScopeName = "MyScope",
    AutomaticAuthenticate = true,
    AdditionalScopes = new[] { "MyScope" }
});

app.UseCookieAuthentication(new CookieAuthenticationOptions
{
    AuthenticationScheme = "Cookies",
    CookieName = ".myCookieName.rmkt",
    ExpireTimeSpan = idsrvConfiguration.Cookie.Expiration,
    CookieSecure = CookieSecurePolicy.Always,
    SlidingExpiration = true
});

var oidcOptions = new OpenIdConnectOptions
{
    AuthenticationScheme = "oidc",
    ClaimsIssuer = urlBuilderConfiguration.Auth.Url,
    SignInScheme = CookieAuthenticationDefaults.AuthenticationScheme,
    Authority = idsrvConfiguration.IdentityServerEndpoint,
    RequireHttpsMetadata = false,
    PostLogoutRedirectUri = urlBuilder.Home,
    ClientId = idsrvConfiguration.Clients.Remarketing.Id,
    ClientSecret = idsrvConfiguration.Clients.Remarketing.Secret,
    ResponseType = "code id_token",
    GetClaimsFromUserInfoEndpoint = true,
    SaveTokens = false, // https://auth0.com/docs/quickstart/webapp/aspnet-core/04-storing-tokens
    Scope =
    {
        idsrvConfiguration.Scopes.Frontoffice,
        "openid",
        "profile",
        "email",
        "roles"
    },
    TokenValidationParameters = new TokenValidationParameters()
    {
        IssuerSigningKey = new X509SecurityKey(encryptingCertificate),
        NameClaimType = JwtClaimTypes.Name,
        RoleClaimType = JwtClaimTypes.Role,
    },
    Events = new OpenIdConnectEvents()
    {
        OnRedirectToIdentityProvider = ctx =>
        {
            // APIs must return 401 not 302
            if (ctx.ProtocolMessage.RequestType == OpenIdConnectRequestType.Authentication)
            {
                var isAjax = ctx.Request.Headers["X-Requested-With"] == "XMLHttpRequest";

                if (isAjax)
                {
                    ctx.Response.StatusCode = (int)HttpStatusCode.Unauthorized;
                    ctx.HandleResponse();
                    return Task.FromResult(0);
                }
            }
            return Task.FromResult(0);
        }
    }
};
```

If I comment out the UseIdentityServerAuthentication (and remove the library) the cookie authentication works well otherwise not.

Any hint?

**Comment by leastprivilege** [comment]
We haven't migrated to 1.1 yet. Consider yourself on the bleeding edge. Will have a look at it once again he rest of the ecosystem (e.g. Xunit) have caught up as well.

**Comment by imperugo** [comment]
Cool.
If you need any help to replicate or more info about my configuration let me know.

**Comment by YZahringer** [comment]
Xunit should work with ASP.NET Core 1.1: https://github.com/xunit/xunit/issues/1031

**Comment by leastprivilege** [comment]
You see the problem? It's all a hack.

The official wording from the xunit homepage:

> The examples shown here are done with xUnit.net 2.2 Beta 2, xUnit.net .NET CLI runner 2.2 Preview 2, and .NET CLI 1.0 Preview 2 (including .NET Core 1.0 RTM). Attempting to use any version of .NET CLI other than the supported version will result in indeterminate behavior, and is not officially supported.

**Comment by Tratcher** [comment]
Probably related to https://github.com/aspnet/Security/issues/1044 and having multiple automatic challenge middleware.

**Comment by leastprivilege** [comment]
I didn't follow the thread. What do I need to do to fix this?

**Comment by Tratcher** [comment]
It looks like the conflict is between OIDCOptions.AutomaticChallenge = true (default), and IdentityServerAuthenticationOptions.AutomaticChallenge = true (default)
https://github.com/IdentityServer/IdentityServer4.AccessTokenValidation/blob/9b03c2fa9e79416ae979d7fec023e347ae1259ea/src/IdentityServer4.AccessTokenValidation/IdentityServerAuthenticationOptions.cs#L22
https://github.com/aspnet/Security/blob/dev/src/Microsoft.AspNetCore.Authentication.OpenIdConnect/OpenIdConnectOptions.cs#L49

One of the two needs to be turned off. Which one is up to the app. @imperugo can you give that a try?

Multiple automatic challenge middleware has never been recommended/supported, but there was a change in 1.1 where the middleware order no longer mitigates having multiple. We'll see if there's anything we can do to improve this.

**Comment by imperugo** [comment]
Hi @Tratcher 
I tried to put `AutomaticChallenge` to false on `UseIdentityServerAuthentication` method and also on `OpenIdConnectOptions` class but nothing changes.
I'm not redirect to the login page. Still getting 401

**Comment by leastprivilege** [comment]
Try commenting out the IdSrv MW and see if this changes anything.

**Comment by imperugo** [comment]
in this case the redirect works, but not the part of apis where I use it to protect using bearer

**Comment by leastprivilege** [comment]
Generally I would not recommend mixing web UI (cookies) and APIs (tokens) in the same project. You have to be very careful that they don't mix (e.g. an API accepting a cookie based identity).

It seems you are now experiencing another side-effect.

There seems to be a bug with our challenge options which didn't happen in 1.0 due to the breaking change in behavior in 1.1 - I will have a look.

**Comment by imperugo** [comment]
Thanks for the answer.
I'll try to split the APIs authentication and Cookie Authentication in two different applications (it is something I'm carrying from an old version of the app).

**Comment by YZahringer** [comment]
@imperugo this workaround may help you:
```cs
app.UseWhen(context => context.Request.Path.StartsWithSegments(new PathString("/api")), builder =>
{
    builder.UseIdentityServerAuthentication(new IdentityServerAuthenticationOptions
    {
        AutomaticChallenge = false,
        AutomaticAuthenticate = true
    });
});
app.UseWhen(context => !context.Request.Path.StartsWithSegments(new PathString("/api")), builder =>
{
    var cookieAuthenticationOptions = new CookieAuthenticationOptions
    {
        AutomaticChallenge = false,
        AutomaticAuthenticate = false
    };
    app.UseCookieAuthentication(cookieAuthenticationOptions);
    app.UseOpenIdConnectAuthentication(new OpenIdConnectOptions
    {
        AutomaticChallenge = true,
        AutomaticAuthenticate = true,
                    
        SignInScheme = cookieAuthenticationOptions.AuthenticationScheme
    });
});
```

**Comment by Tratcher** [comment]
`[Authorize(AuthenicationScheme="Bearer")] ` is the recommended way to handle a secondary auth scheme.

**Comment by imperugo** [comment]
@Tratcher already tried with no effects.
@YZahringer thanks, seems i nice solution.

Right now I'm trying to split the authentication with two different applications, if it doesn't solve the problem I'll try to use `UseWhen` method

**Comment by ChristianRiedl** [comment]
I think it is a quite natural approach to have a single web service supporting browser MVC apps with cookie authentication  and native apps calling the api with bearer authentication. In my opinion it was one of the nice  features of AspNetCore that there are no substantial differences between API and  MVC controllers. I hope there will be a solution.

**Comment by brockallen** [comment]
> I think it is a quite natural approach to have a single web service supporting browser MVC apps with cookie authentication and native apps calling the api with bearer authentication.

Not at all. Those are two styles of apps and have fundamentally different security requirements. They should be segregated into separate hosts, or at least with a `Map` if they're in the same host.

**Comment by GavinSutherland** [comment]
@brockallen 

Appreciate the comment above is old but what are the specific security risks with having a single mvc app support both cookie authentication and bearer authentication?

Thanks

**Comment by brockallen** [comment]
You don't want your APIs accidentally accepting and trusting cookies. If you have APIs/Bearer and MVC/Cookies in the same pipeline then it's easy to trust the wrong thing in the wrong framework.

**Comment by GavinSutherland** [comment]
OK thanks @brockallen

**Comment by tutok** [comment]
@brockallen what if cookie is alternative way (to Authentication header) of transporting authentication ticket?
