### ISSUE TITLE
Null Ref using UseIdentityServerAuthentication with IdentityServerAuthenticationOptions

### ISSUE THREAD

**Issue by Gekctek** [IdentityServer/IdentityServer4.AccessTokenValidation#40]
when calling app.UseIdentityServerAuthentication(options) where options is of type IdentityServerAuthenticationOptions, there is sometimes a null reference exception. It seems to occur if options.ValidateScope = false because when it convert to the CombinedAuthenticationOptions the ScopeValidationOptions is null and the helper tries to use it
```
if (options.ScopeValidationOptions.AllowedScopes.Any())
{
    app.AllowScopes(options.ScopeValidationOptions);
}

**Comment by brockallen** [comment]
Fixed. Thanks for letting us know.
