### ISSUE TITLE
Authentication Middleware Settings

### ISSUE THREAD

**Issue by senj** [IdentityServer/IdentityServer4.AccessTokenValidation#42]
Hey guys,

as soon as I access an anonymous page (e.g. documentation) on the service, I get a wall of this log messages.
![image](https://cloud.githubusercontent.com/assets/5556013/21807556/991e80be-d73f-11e6-9b7a-c1ec2dcf5c6f.png)

My Config:

```
IdentityServerAuthenticationOptions options = new IdentityServerAuthenticationOptions
                    {
                        Authority = stsUrl,
                        AutomaticAuthenticate = true,
                        AutomaticChallenge = true
                      }
```
and a policy with
```
 policyBuilder.AddAuthenticationSchemes("Bearer");
```

Do I have to add a something or is it normal to have those messages for anonymous users?

**Comment by leastprivilege** [comment]
Well - one is debug. The other is saying that no token is found.

This is "normal".
