### ISSUE TITLE
ApiSecret is Required for Client with AccesTokenType = Reference

### ISSUE THREAD

**Issue by h2chch** [IdentityServer/IdentityServer4.AccessTokenValidation#45]
I have used the sample provided on https://github.com/IdentityServer/CrossVersionIntegrationTests to use IdentityServer4.AccessTokenValidation package validating the token issued by IdentityServer3. I noticed that for the client with AccessTokeType set to "Reference" type, the Scope needs to have ScopeSecrets set. Thus the API which validates the token is required to set ApiSecret. Why now the ScopeSecrets becomes mandatory for Reference type client? 

![image](https://cloud.githubusercontent.com/assets/1444973/22064207/7929537c-ddbd-11e6-8079-a6f8edd1c2f8.png)

**Comment by leastprivilege** [comment]
Because the new endpoint requires authentication.
