### ISSUE TITLE
Issuer = LOCAL AUTHORITY

### ISSUE THREAD

**Issue by etrafiee** [IdentityServer/IdentityServer4.AccessTokenValidation#47]
Hi, 
Since I switched to Reference tokens, the issuer field of claims does no longer have the actual value of my identity server URL, instead it has "LOCAL AUTHORITY" value.

Is there any setting that I am missing?

**Comment by leastprivilege** [comment]
That's true. What's the scenario - and why do you need it?

**Comment by etrafiee** [comment]
In my previous scenario - using Jwt tokens - I was checking the claim issuer as an extra security step.
is it unnecessary?

**Comment by leastprivilege** [comment]
yes. The issuer gets already checked at token validation time.
