### ISSUE TITLE
Call a secure api from an unauthenticated page add items to cookie.

### ISSUE THREAD

**Issue by mikeandersun** [IdentityServer/IdentityServer4.AccessTokenValidation#52]
I have a MVC view that contains a list of items. any item has an angularjs component that call a secure api.
When the use is logged in all things work fine.
When the user not logged in :
for any list item(api call) one pair of the the following items add to the cookie. 
so the cookie reaches the cookie size restriction .
![oidcbug](https://cloud.githubusercontent.com/assets/548021/23824194/5b1e9a70-0687-11e7-8b9f-460e0228e39e.png)

**Comment by leastprivilege** [comment]
This is unrelated to IdentityServer. Ask Microsoft.
