### ISSUE TITLE
No validator configured for reference token. Ensure ApiName and ApiSecret have been configured to use introspection

### ISSUE THREAD

**Issue by hazelmyth** [IdentityServer/IdentityServer4.AccessTokenValidation#54]
Get this error when validating access token against Identity server after upgrading package from "1.0.1-rc3" to "1.1.0". Currently we are using IdentityServer4 version "1.0.0-rc1-update2". 
Is there any version of IdentityServer4 working with IdentityServer4.AccessTokenValidation version "1.1.0"?

**Comment by leastprivilege** [comment]
I would recommend you upgrade everything to latest first.

**Comment by hazelmyth** [comment]
Thank you @leastprivilege , just realize that our IdentityServer4 is way too much out of date and so many changes has been made since then.
