### ISSUE TITLE
JWT "validation" with encryption algorithm set to 'none'

### ISSUE THREAD

**Issue by RomanBorysenok** [IdentityServer/IdentityServer4.AccessTokenValidation#59]
Hello,

Thank you for your work!
I have one question regarding "validation" of JWT that is encrypted with algorithm set to 'none'.
Currently, for development purpose encryption alg is set to 'none', but I'm finding the way how to properly handle this kind of scenario.
As I understand when JWT is encrypted with 'none' alg, then there is no signature in this JWT.
As a result of that I'm getting the Error when trying to verify it : ''IDX10504: Unable to validate signature, token does not have a signature".
So I'm wondering is this type of scenario is supported?
As I know, https://www.npmjs.com/package/jsonwebtoken is supporting this kind of scenario:
`jwt.verify(bearerToken, null, { algorithms: ['none'] });`

Thanks!

**Comment by leastprivilege** [comment]
I don't follow. IS4 does not support JWT encryption OOB.
