### ISSUE TITLE
How to ensure token has not been tampered

### ISSUE THREAD

**Issue by realavaloro** [IdentityServer/IdentityServer4.AccessTokenValidation#6]
I'm testing IdentityServer4 and AccessTokenValidation.
At my API's http pipeline I've got the following:

```
//CORS
app.UseCors(policy =>
{
        var originUris = Configuration.GetSection("Cors:OriginUris").Get<List<string>>();
        policy.WithOrigins(originUris.ToArray());
        policy.AllowAnyHeader();
        policy.AllowAnyMethod();
});

JwtSecurityTokenHandler.DefaultInboundClaimTypeMap.Clear();
app.UseJwtBearerAuthentication(options =>
{
      if (_hostEnv.IsDevelopment())
      {
            //for development it is not required https in Authority Uri
            options.RequireHttpsMetadata = false;
      }
      options.Authority = Configuration["Authentication:AuthorityUri"];
      options.Audience = Configuration["Authentication:AudienceUri"]; //should this be URL for the receiver of the token
      options.AutomaticAuthenticate = true;
      options.AutomaticChallenge = true;
});

     var userScopes  = Configuration.GetSection("Authentication:UserScopes").Get<List<string>>();

     app.UseIdentityServerAuthentication(options =>
     {
           options.Authority = Configuration["Authentication:AuthorityUri"];
           options.ScopeName = "api1";
           options.AdditionalScopes = userScopes;
           options.ScopeSecret = "secret";
           options.AutomaticAuthenticate = true;
           options.AutomaticChallenge = true;
      });
```

I suppose there is no documentation ready yet on how this works, but as I understood this token validation only validates that the access_token has been issued by the AuthorityUri and later the UseIdentityServerAuthentication middleware checks whether it has the required scopes.

**Is there any built in capability to detect whether an access token has been tampered?**

I've replaced the last character of my access_token with a random one and the authentication/token validation seems to remain valid (and I think it shouldn't so I must do something about it if this is not supported)

**Comment by leastprivilege** [comment]
The middleware does check the signature yes.

You need to change more than a single character - you may have hit some padding.

**Comment by leastprivilege** [comment]
Btw - why are you using both middlewares?

**Comment by realavaloro** [comment]
After seeing your Sample for an API here https://github.com/IdentityServer/IdentityServer4.Samples/blob/dev/Mvc/src/SampleApi/Startup.cs
I see it's not necessary to use the ```UseJwtBearerAuthentication``` middleware. Thanks for that.

Now with only the ```UseIdentityServerAuthentication``` middleware plugged into my app's pipeline it seems to work as expected.

Modifying the last character of the Bearer token will trigger an error ```IDX10503: Signature validation failed``` so it all looks great!
