### ISSUE TITLE
Use IdentityServer4.AccessTokenValidation to validate IdentityServer3 access tokens

### ISSUE THREAD

**Issue by ysmoradi** [IdentityServer/IdentityServer4.AccessTokenValidation#65]
I use Identity Server 3 with implicit & resource owner flows.
When my ASP.NET/Katana app receives a request, it contains access token in its headers. My ASP.NET/Katana app has certificate, secret and uses local validation to validate access tokens. It sends no request to identity server to validate tokens and I'm happy with this configuration.
As I know, identity server creates access tokens based on standards such as OAuh 2.0.
The question is: Can I use IdentityServer4.AccessTokenValidation to validates access tokens of IdentityServer3? I've a new asp.net core based app on full .net framework. I tested IdentityServer3.AccessTokenValidation.Integration.AspNetCore and that worked like a charm (-:
But to achieve better performance, I'd like to configure my app with IdentityServer4.AccessTokenValidation
Thanks in advance.

**Comment by brockallen** [comment]
> Can I use IdentityServer4.AccessTokenValidation to validates access tokens of IdentityServer3

Yes.
