### ISSUE TITLE
Using private key JWT to authenticate APIs

### ISSUE THREAD

**Issue by ItielBeeri** [IdentityServer/IdentityServer4.AccessTokenValidation#66]
Clients can authenticate themselves without sharing any secret with IdSvr, which, on the client side, requires only a little work on JWT preparation and submission using TokenClient.
However, I couldn't figure out how it could be done for APIs, when they need to authenticate themselves against the introspection endpoint, using IdentityServer[3/4].AccessTokenValidation.
Is there any configuration that makes it possible for API to authenticate using a self-signed JWT? Assuming the IdSvr itself has been configured as appropriate.

**Comment by brockallen** [comment]
Yes, API signed JWTs should work in the same was they do fro clients: https://github.com/IdentityServer/IdentityServer4.Samples/tree/release/Clients/src/ConsolePrivateKeyJwtClient

**Comment by ItielBeeri** [comment]
But how do I configure the AccessTokenValidation middleware for that authentication type?

**Comment by brockallen** [comment]
It doesn't support that. You can enhance it and submit a PR.
