### ISSUE TITLE
IntrospectionBackChannelHandler client request

### ISSUE THREAD

**Issue by mangelarilla** [IdentityServer/IdentityServer4.AccessTokenValidation#69]
I am using a custom MessageHandler for the IntrospectionBackChannelHandler configuration property.

The thing is that I am trying to add a custom header to the instrospection request based on a header of the client request to the resource, but I cannot access the client request, neither by IHttpContextAccessor, it seems to be executed before populating this context.

**Comment by leastprivilege** [comment]
Yes - that probably doesn't work.

You could fallback to the IntrospectionClient class in IdentityModel and write your own middleware to accommodate for that scenario.

**Comment by mangelarilla** [comment]
I followed your advice and I've built a middleware for the Introspection endpoint, I guess this has to replace the `app.UseIdentityServerAuthentication`, but I think I've missed something related with NopAuthenticationMiddleware as I get a 404 in the response and IDSRV logs tell me Bearer was not authenticated (from the NopAuthenticationMiddleware).

**Comment by mangelarilla** [comment]
Ok, found the problem. I was doing a bad assumption on the endpoint and the connect/introspect was not being added to the path causing all these troubles.
Updated the gist: [Gist](https://gist.github.com/mangelarilla/e537de0f4313934e09dc4886180036d0)
