### ISSUE TITLE
Advantage over UseJwtBearerAuthentication

### ISSUE THREAD

**Issue by damienbod** [IdentityServer/IdentityServer4.AccessTokenValidation#7]
This is just a question. What's the advantage of using this instead of UseJwtBearerAuthentication for the resource server?

Greetings Damien

**Comment by leastprivilege** [comment]
it has support for reference tokens as well - and caching when it is implemented.

**Comment by dottilotti** [comment]
OK, thanks

**Comment by damienbod** [comment]
thanks
