### ISSUE TITLE
Does it work with AspNetCore 2.0 ?

### ISSUE THREAD

**Issue by valeriob** [IdentityServer/IdentityServer4.AccessTokenValidation#70]
I'm migrating an application from katana to aspnetcore 2.0.
Given https://github.com/aspnet/Security/issues/1310 i do not understand if i have to bring everything is this new services.AddAuthentication world or not, i see that IdentityServer4.AccessTokenValidation still use a classic middle-ware approach.
Do you have any guidance ?
Thanks

**Comment by leastprivilege** [comment]
No. Use the MS JwtBearer middleware instead.
