### ISSUE TITLE
IdentityServer4.AccessTokenValidation doesn't support Asp.Net Core 2.0?

### ISSUE THREAD

**Issue by mokeyish** [IdentityServer/IdentityServer4.AccessTokenValidation#71]

**Comment by leastprivilege** [comment]
or the other way round rather.

**Comment by cormacrelf** [comment]
Does this call for a bump to 2.0 (alongside IdentityModel.AspNetCore.OAuth2Introspection & others) and keep a 1.x branch around for maintenance?

Would you like any help or are you ticking along just fine?

Some handy references: 

[ASP.NET Auth 2.0 overview](https://github.com/aspnet/Announcements/issues/262)

[Microsoft.AspNetCore.Authentication.JwtBearer 2.0](https://github.com/aspnet/Security/tree/dev/src/Microsoft.AspNetCore.Authentication.JwtBearer) (this is good as an implementation reference, most importantly the new configuration scheme through services and the `IAuthenticationHandler` implementation.

[Migrating to auth 2.0 for end users](https://docs.microsoft.com/en-us/aspnet/core/migration/1x-to-2x/identity-2x)

**Comment by kspearrin** [comment]
Yup, getting errors when trying to `app.UseIdentityServerAuthentication(...`

**Comment by mokeyish** [comment]
Thank you，I have found solution for this problem。

**Comment by kspearrin** [comment]
@mokeyish what is the solution?

**Comment by mokeyish** [comment]
@kspearrin
 `            services.AddJwtBearerAuthentication(options =>
                {
                    options.Authority = http://xxx;
                    options.RequireHttpsMetadata = false;
                    options.Audience = "api1";
                });
               app.UseAuthentication();`

**Comment by kspearrin** [comment]
So we no longer use this library?

**Comment by cormacrelf** [comment]
Well, Jetbearer is only half the functionality. It can't dereference access tokens that aren't plain JWTs.

**Comment by mokeyish** [comment]
@kspearrin Yes，we no longer use this library，Asp.Net Core 2.0 has already wrapped up authentication  functionality.Asp.Net core 2.0 recognize different  authentication  by token_type.

**Comment by urbanhusky** [comment]
This sounds like this issue is still valid when using reference tokens?

**Comment by cormacrelf** [comment]
You could move it to OAuth2Introspection?
