### ISSUE TITLE
ID4 AccessTokenValidation vs Microsoft JwtBearer

### ISSUE THREAD

**Issue by ppdAustin** [IdentityServer/IdentityServer4.AccessTokenValidation#73]
I have switched my AspNetCore 2.0 project over to MS's JwtBearer as recommended in [IdentityServer4 AccessTokenValidation Issue 72](https://github.com/IdentityServer/IdentityServer4.AccessTokenValidation/issues/72) and [IdentityServer4 Main Issue 1055](https://github.com/IdentityServer/IdentityServer4/issues/1055).  I am wondering should I switch back once IdentityServer4 is updated to support AspnetCore 2.0?  What does this project gain me that the Microsoft library does not?

Don't get me wrong, I am definitely keeping IdentityServer4 for my OAuth server, just wondering if I really need it on the client side too?

**Comment by brockallen** [comment]
We support introspection.

**Comment by leastprivilege** [comment]
If all you need is JWTs then you can use the Microsoft middleware.
