### ISSUE TITLE
Prevent invalid token requests spamming identityserver

### ISSUE THREAD

**Issue by ThatDeveloper** [IdentityServer/IdentityServer4.AccessTokenValidation#79]
With EnableCaching = true and CacheDuration = TimeSpan.FromMinutes(1) I can prevent my API from calling the IdentityServer on every request. What would you think about using this CacheDuration for invalid Bearer tokens too? Because I have some third party users spamming my identityserver because they receive 401 Unauthorized.. If the bad request would be chached too we could reduce that amount drasticly.

Greets Manuel

**Comment by leastprivilege** [comment]
OTOH - this means someone can flood your cache with invalid data..

**Comment by leastprivilege** [comment]
@brockallen

**Comment by ThatDeveloper** [comment]
Well I thought of that too, but if I have 10 applications using identityserver to validate reference tokens, and someone spams the applications with invalid requests, then the identityserver is the bottleneck. :/

**Comment by ThatDeveloper** [comment]
At the moment i cache the data with the setting on the api for 1 minute. But only the successfulm would you recommend something else?

**Comment by leastprivilege** [comment]
I think this is a good idea - but the wrong repo

Tracked here:

https://github.com/IdentityModel/IdentityModel.AspNetCore.OAuth2Introspection/issues/19
