### ISSUE TITLE
"Bad" Token Response

### ISSUE THREAD

**Issue by ojhp** [IdentityServer/IdentityServer4.AccessTokenValidation#8]
Hi,

Just wondering whether there are any plans to handle exceptions thrown due to bad tokens (I tried removing the first character) as 401 errors rather than the 500 error I currently seem to be getting.

I've been looking at the SampleApi project from the samples repository, and found that passing no token, or an expired token responds with a 401 error, passing a token for another scope returns a 403, but passing a token that cannot be parsed causes an unhandled exception which returns a 500.

I've managed to work around this for my own purposes by adding additional steps to the MVC pipeline to detect when an exception is thrown from the authentication part of the pipeline and handle that specially, but just wondered if there was a simpler way or if this is the expected behaviour.

**Comment by leastprivilege** [comment]
IIRC that is a problem with the RC1 token middleware from MS - some errors are not caught and bubble up. That has been long fixed. But since then there was no new release.

**Comment by ojhp** [comment]
Thanks for the response, I thought it looked like the Microsoft bits shouldn't be doing that. Will go with a workaround for now and keep an eye out for any further releases of the JWT middleware.

For anyone else with this issue, my workaround is to add the following two bits of middleware:
* [AuthenticationExceptionHandlerMiddleware](https://gist.github.com/ojhp/dfd40295d8e3e73d3681)
* [AuthenticationSuccessMarkerMiddleware](https://gist.github.com/ojhp/0a38819197f6d3f0d634)

The AuthenticationExceptionHandlerMiddleware goes into the pipeline before the IdentityServer authentication, catches exceptions and returns a 401 so long as the authentication step didn't succeed, the AuthenticationSuccessMarkerMiddleware goes in after so exceptions in the rest of the pipeline aren't handled the same. I'm open to any better suggestions though.

Thanks again
