### ISSUE TITLE
AuthenticationOptions not found in Microsoft.AspNetCore.Authentication

### ISSUE THREAD

**Issue by ernestjohn** [IdentityServer/IdentityServer4.AccessTokenValidation#81]
Hello, the package AuthenticationOptions not found in Microsoft.AspNetCore.Authentication Severity	

**Reference to type 'AuthenticationOptions' claims it is defined in 'Microsoft.AspNetCore.Authentication', but it could not be found**	

This only comes when I'm using aspnetcore 2.0 with the *.All package. 
Is there a missing reference?

**Comment by leastprivilege** [comment]
You need to use the RC1 with ASP.NET Core 2

**Comment by mymaizi** [comment]
If you use rc1+asp.net core 2, new errors will be prompted, and.Useidentity******* cannot find them

**Comment by aiyowa** [comment]
I'm using aspnetcore 2+ rc2.but it's still not work.

**Reference to type 'AuthenticationOptions' claims it is defined in 'Microsoft.AspNetCore.Authentication', but it could not be found**

**Comment by leastprivilege** [comment]
Final version has been released now.
