### ISSUE TITLE
Prefix child introspection and jwt authentication configurations with current prefix 

### ISSUE THREAD

**Issue by pksorensen** [IdentityServer/IdentityServer4.AccessTokenValidation#86]
If users want to add multiple AddIdentityServerAuthentication with different schemas in their startup. (Api that needs to authenticate against two different scopes or what not). (I am unsure if this is a valid usecase)

```
AddIdentityServerAuthentication("schema1", ...)
AddIdentityServerAuthentication("schema1", ...)
```
then the child authentication calls of the middleware will hit the same two child authentication configurations for jwt and introspection.

I solved it when I played with it by adding a prefix based on current schema.

https://github.com/pksorensen/IdentityServer4.AccessTokenValidation/blob/24997f7715cb3f438dbece453bef3c16e51817a8/src/IdentityServer4.AccessTokenValidation/IdentityServerAuthenticationHandler.cs#L58

https://github.com/pksorensen/IdentityServer4.AccessTokenValidation/blob/24997f7715cb3f438dbece453bef3c16e51817a8/src/IdentityServer4.AccessTokenValidation/IdentityServerAuthenticationExtensions.cs#L46

**Comment by brockallen** [comment]
Done here: https://github.com/IdentityServer/IdentityServer4.AccessTokenValidation/commit/104f0b973892f7179dc45c21a8cad0c8ec4d88fb
