### ISSUE TITLE
AllowedScopes disappear

### ISSUE THREAD

**Issue by Bidou44** [IdentityServer/IdentityServer4.AccessTokenValidation#87]
After updating this package to the 2.0.0-rc2, I noticed that the AllowScopes property on the IdentityServerAuthenticationOption disappear (same problem with AutomaticChallenge).

How can I set these properties in this version?

**Comment by brockallen** [comment]
Use ASP.NET Core authorization policies. There was an issue to add a policy for this: https://github.com/IdentityServer/IdentityServer4.AccessTokenValidation/issues/76

And looks like here's the code: https://github.com/IdentityServer/IdentityServer4.AccessTokenValidation/blob/dev/src/IdentityServer4.AccessTokenValidation/AuthorizationPolicyExtensions.cs
