### ISSUE TITLE
Configure default clock skew

### ISSUE THREAD

**Issue by aiyowa** [IdentityServer/IdentityServer4.AccessTokenValidation#90]
The MS JWT handler has a default clock skew of 5 minutes. So is there any way to configure/change the default clock skew value?

**Comment by leastprivilege** [comment]
I don't think we expose that setting directly.

* which version are you using?
* do you need to support JWTs and reference tokens in the same API?

**Comment by aiyowa** [comment]
* I using V2.0.0.
* Need support it.

**Comment by leastprivilege** [comment]
OK - we don't expose that directly. I think you can pass in the JwtBearer options directly - but this requires you to do all the config.

Why do you want to change it?

**Comment by aiyowa** [comment]
I want to change it because I hope the token expire time no "delay"(just for test).
Thanks for response.

**Comment by aiyowa** [comment]
I want to change it because I hope the token expire time no "delay"(just for test).
Thanks for response.

**Comment by elfalem** [comment]
I would also appreciate the ability to change the skew for testing purposes.

**Comment by leastprivilege** [comment]
What are you testing?

**Comment by elfalem** [comment]
I'm testing the automatic renewal of tokens that are about to expire. To avoid waiting, I set short lifetimes on the tokens. However, with the skew, even a token with a lifetime of 1 second effectively has a lifetime of 5 minutes and 1 second.

**Comment by leastprivilege** [comment]
OK - will add it.

**Comment by leastprivilege** [comment]
nuget pushed - give it a try.

**Comment by elfalem** [comment]
I tried it and it works. Thanks @leastprivilege for the prompt response!

**Comment by ruskindantra** [comment]
OMG @elfalem I did some vigorous testing around expiry times and eventually realised that "5 mins" was the default token lifetime without realising it was the clock skew.  Appreciate this thread :)
