### ISSUE TITLE
Should ClaimsIdentity should have IsAuthenticated as false by default ?

### ISSUE THREAD

**Issue by sirajmansour** [IdentityServer/IdentityServer4.AccessTokenValidation#92]
As per my understanding IdentityServer could be used for authorisation, authentication or both. In case one is not using OpenID and only relying on Idsrv to control access to an API, shouldn't this middleware create and set the `ClaimsIdentity` with `IsAuthenticated` as `false` by default ?

**Comment by leastprivilege** [comment]
If the token is valid -- an authenticated ClaimsIdentity is produced.

Authorization is a separate app specific concern.
