### ISSUE TITLE
Can IdentityServer4 and IdentityServer4.AccessTokenValidation in same project?

### ISSUE THREAD

**Issue by seven1986** [IdentityServer/IdentityServer4.AccessTokenValidation#94]
Before I use IdentityServer4 with AspNet Core 2.0 , 
Now I want open some Apis that's belong IdentityServer such as  client, apiresource, users, so need authrize client token.

 Can add this with idserver4 in same project?

thanks

**Comment by leastprivilege** [comment]
https://identityserver4.readthedocs.io/en/release/topics/add_apis.html
