### ISSUE TITLE
Multiple Api resources for identity server authentication

### ISSUE THREAD

**Issue by hazelmyth** [IdentityServer/IdentityServer4.AccessTokenValidation#95]
Can I authenticate again more than one api resources in a single web api project?

The situation is like this:
I have one web api project which include api endpoints for both the back office user (administrator) and normal user. I have two Api resources specified in Identity Server, one is "admin", the other is "normal_user".  When doing access token validation, I could only specify one api resource with the api name like
`services.AddAuthentication(IdentityServerAuthenticationDefaults.AuthenticationScheme)
    .AddIdentityServerAuthentication(options =>
    {
        options.Authority = "https://demo.identityserver.io";
        options.ApiName = "admin";
    });
`
. Yet how could I deal with the other api resource?

**Comment by leastprivilege** [comment]
I would rather use one api resource - but two scopes.

**Comment by hazelmyth** [comment]
I see, thank you very much.
