### ISSUE TITLE
MissingMethodException when used in ASP.NET Core 2.0 with full .NET Framework

### ISSUE THREAD

**Issue by freddy-ae** [IdentityServer/IdentityServer4.AccessTokenValidation#97]
We've got the following setup:

- Web-Project (ASP.NET Core 2.0 running on .NET Framework 4.6.2)
- BL-Project (Class Library, .NET Framework 4.6.2)
- Shared-Project (.NET Standard 2.0)

No problems so far...
When referencing and using this library, we get the following (shortened) exception:
--> MissingMethodExcepion: DiscoveryClient.ParseUrl

It seems, that some references/types (maybe System.ValueTuple) gets mixed and then the web cannot be startet anymore.

Workaround:
Change project type to Class Library, .NET Framework 4.6.2

Is there a better way to integrated this library in the project setup above?
We don't want to maintain a separate code base because of the different project type....

**Comment by leastprivilege** [comment]
It's a Microsoft tooling bug. It's gonna be fixed at some point.

**Comment by leastprivilege** [comment]
here's the announcement

https://github.com/dotnet/standard/issues/567
