### ISSUE TITLE
Method not found IdentityModel.Client. DiscoveryClient.ParseUrl(System.String)

### ISSUE THREAD

**Issue by edtim8** [IdentityServer/IdentityServer4.AccessTokenValidation#99]
When I updated to IdentityServer4.AccessTokenValidation **2.1.0**, a crisis problem appeared.

fail: Microsoft.AspNetCore.Server.Kestrel[13]
      Connection id "0HL9P6Q5123R7", Request id "0HL9P6Q5123R7:00000001": An unhandled exception was thrown by the appli
cation.
System.MissingMethodException: Method not found: 'System.ValueTuple`2<System.String,System.String> IdentityModel.Client.
DiscoveryClient.ParseUrl(System.String)'.
   at IdentityServer4.AccessTokenValidation.IdentityServerAuthenticationOptions.ConfigureJwtBearer(JwtBearerOptions jwtO
ptions)

**I can't fix it..... help ...**

**Comment by edtim8** [comment]
![image](https://user-images.githubusercontent.com/7846368/33511524-f34d3090-d756-11e7-8e45-c92a3f91db24.png)

**Comment by brockallen** [comment]
Did you mean to close this?

**Comment by andymac4182** [comment]
We are getting the same issue @brockallen . It appears to be related to .NET 4.7 being installed. Any help would be great.

**Comment by leastprivilege** [comment]
It's a Microsoft tooling issue. They said they gonna fix it "soon".

**Comment by darkurse** [comment]
Is there a workaround we can do in the meantime ?

**Comment by leastprivilege** [comment]
try targeting 461, or 47x or netcoreapp2.0 specifically - can't remember which one.

**Comment by leastprivilege** [comment]
yea - that's a pretty sad story.

Try targeting the latest 4.7 explicitly.

**Comment by leastprivilege** [comment]
Let me know if that works.

**Comment by darkurse** [comment]
It works with 4.7. Sorry for the late answer but I had to extract out the legacy dependencies in another assembly so that I could use 4.7 on the main assembly.
